-- create tables
create table create_table_standings (
    id                             number not null constraint create_table_stand_id_pk primary key,
    standing_idvarchar210primary_k varchar2(4000),
    matches_played_integer_not_nul varchar2(4000),
    win_integer_not_null           varchar2(4000),
    drawn_integer_not_null         varchar2(4000),
    lose_integer_not_null          varchar2(4000),
    goals_for_integer_not_null     varchar2(4000),
    goals_againts_integer_not_null varchar2(4000),
    goal_difference_integer_not_nu varchar2(4000),
    points_integer_not_null        varchar2(4000),
    matchs_match_idvarchar210_not_ varchar2(4000),
    team_idnumber2                 number
)
;

create table order_by_match_id (
    id                             number not null constraint order_by_match_id_id_pk primary key
)
;


-- triggers
create or replace trigger create_table_standings_biu
    before insert or update 
    on create_table_standings
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
end create_table_standings_biu;
/

create or replace trigger order_by_match_id_biu
    before insert or update 
    on order_by_match_id
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
end order_by_match_id_biu;
/

-- load data
 
-- Generated by Quick SQL Sunday October 25, 2020  04:44:51
 

LEAGUES

insert into leagues
(League_ID, League_Name, Start_Date, End_Date, Amount_Of_Team, Amount_Of_Stadium, Amount_Of_Match, Amount_Of_Round)
values
('L001', 'Liga Indonesia', '21-Jan-2021', '21-Dec-2021', 18, 18, 34, 2)

SELECT * FROM LEAGUES

======================================
TEAMS

create sequence seq_teams_seq
increment by 1
start with 1
maxvalue 18
nocache
nocycle

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persija', 'Jakarta', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persib', 'Bandung', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persebaya', 'Surabaya', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Arema', 'Malang', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persipura', 'Papua', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values  (seq_teams_seq.nextval, 'Persita', 'Tanggerang', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persikabo', 'Bogor', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Bali United', 'Bali', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persela', 'Lamongan', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persik', 'Kediri', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Sriwijawa FC', 'Palembang', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Madura United', 'Madura', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'PSIS', 'Semarang', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'PSS', 'Sleman', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'PSIM', 'Yogyakarta', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'PSM', 'Makassar', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persiraja', 'Aceh', 'L001')

insert into teams (team_id, team_name, province, leagues_league_id)
values (seq_teams_seq.nextval, 'Persis', 'Solo', 'L001')

select * from teams
order by team_id


===========================================================
MANAGEMENTS 


create table management_teams (
management_id varchar2(20) constraint mana_teams_mana_id_pk primary key, 
management_name varchar2(30) Not Null, 
phone_number integer Not Null)  

insert all
into management_teams (management_id, management_name, phone_number)
values ('MT001', 'Bambang', 81293839372)
into management_teams (management_id, management_name, phone_number)
values ('MT002', 'Maman', 87781718832)
select * from dual

select * from management_teams


===========================

PLAYERS

create table players (
management_id varchar2(20) not null,
teams_team_id number(2) not null,
player_id varchar2(10) constraint players_player_id_pk primary key, 
player_code varchar2(10) not null, 
player_name varchar2(30) not null, 
back_number integer not null, 
birth_date date not null, 
weight integer not null, 
height integer not null,
CONSTRAINT mana_id_fk
FOREIGN KEY (management_id)
REFERENCES management_teams (management_id) on delete cascade)

alter table players disable constraint players_player_id_pk cascade


insert into players (management_id, teams_team_id, player_id, player_code, player_name, back_number, birth_date, weight, height)
values ('MT001', 1, 'P100', 'P101', 'Andritany Ardhiyasa', 1, '21-MAR-1980', 80, 170)

insert into players (management_id, teams_team_id, player_id, player_code, player_name, back_number, birth_date, weight, height)
values ('MT001', 1, 'P100', 'P102', 'Otavio Dutra', 6, '21-MAR-1984', 72, 170)

insert into players (management_id, teams_team_id, player_id, player_code, player_name, back_number, birth_date, weight, height)
values ('MT001', 1, 'P100', 'P103', 'Ryuji Utomo', 4, '15-NOV-1986', 72, 170)

insert into players (management_id, teams_team_id, player_id, player_code, player_name, back_number, birth_date, weight, height)
values ('MT002', 2, 'P200', 'P201', 'I Made Wirawan', 8, '20-JUN-1986', 64, 170)

insert into players (management_id, teams_team_id, player_id, player_code, player_name, back_number, birth_date, weight, height)
values ('MT002', 2, 'P200', 'P202', 'Fabiano Beltrame', 12, '26-AUG-1992', 64, 170)

insert into players (management_id, teams_team_id, player_id, player_code, player_name, back_number, birth_date, weight, height)
values ('MT002', 2, 'P200', 'P203', 'Henhen Herdiana', 21, '22-MAR-1989', 80, 171)


select * from players
order by player_id


==============================
COACHES


create table COACHES (
management_id varchar2(20) not null, 
teams_team_id number(2) not null, 
coach_id varchar2(10) constraint coaches_coach_id_pk primary key, 
coach_name varchar2(30) not null,
CONSTRAINT manag_id_fk
FOREIGN KEY (management_id)
REFERENCES management_teams (management_id) on delete cascade)

alter table coaches disable constraint coaches_coach_id_pk cascade

insert into coaches (management_id, teams_team_id, coach_id, coach_name)
values ('MT001', 1, 'C001', 'Sergio Farias')

insert into coaches (management_id, teams_team_id, coach_id, coach_name)
values ('MT002', 2, 'C002', 'Robert Rene Alberts')

select * from coaches

=======================================

MATCHS

insert into matchs (match_id, match_name, status, stadium, score)
values ('M1001', 'Persija VS Persib', 'Selesai', 'GBK',	'2-1')

insert into matchs (match_id, match_name, status, stadium, score)
values ('M1002', 'Persebaya VS Arema', 'Selesai', 'GBT', '1-1')

insert into matchs (match_id, match_name, status, stadium, score)
values ('M1003', 'Persib VS Arema', 'Belum Bertanding', 'SJH',	'-')

insert into matchs (match_id, match_name, status, stadium, score)
values ('M1004', 'Persib VS Persebaya', 'Belum Bertanding', 'GBK', '-')



select * from matchs

=================================

SCHEDULES //disable schedules_matchs_fk dari object browser

alter table SCHEDULES 
disable SCHEDULES_MATCHS_FK cascade

insert all 
into schedules (teams_team_id, matchs_match_id, schedule_id, date_and_time)
values (1, 'M1001', 'S1001', '12-Jan-2021 at 15:00')
into schedules (teams_team_id, matchs_match_id, schedule_id, date_and_time)
values (2, 'M1001', 'S1001', '12-Jan-2021 at 15:00')
select * from dual

insert all
into schedules (teams_team_id, matchs_match_id, schedule_id, date_and_time)
values (3, 'M1002', 'S1002', '17-Jan-2021 at 15:00')
into schedules (teams_team_id, matchs_match_id, schedule_id, date_and_time)
values (4, 'M1002', 'S1002', '17-Jan-2021 at 15:00')
select * from dual


select * from schedules


=========================================

REFEREES // drop

alter table referees
drop constraint REFEREES_SCHEDULES_FK

alter table referees
disable REFEREES_PK

insert all into referees (referee_id, referee_name, schedules_teams_team_id, schedules_matchs_match_id, schedules_schedule_id) 
values ('R001', 'M. Erfan Efendi', '1 vs 2', 'M1001', 'S1001')
into referees (referee_id, referee_name, schedules_teams_team_id, schedules_matchs_match_id, schedules_schedule_id) 
values ('R002', 'Annas Apriliandi', '3 vs 4', 'M1002', 'S1002')
select * from dual

insert all into referees (referee_id, referee_name, schedules_teams_team_id, schedules_matchs_match_id, schedules_schedule_id) 
values ('R003', 'Steven Yubel Poli', '2 vs 4', 'M1003', 'S1003')
into referees (referee_id, referee_name, schedules_teams_team_id, schedules_matchs_match_id, schedules_schedule_id) 
values ('R004', 'Zetman Pangiribuan', '1 vs 3', 'M1004', 'S1004')
select * from dual

select * from referees



==========================================

STATISTIC MATCHS

insert all 
into STATISTIC_MATCHS (STATISTIC_ID, MATCHS_MATCH_ID, PLAYERS_MANAGEMENT_ID, STATISTIC_CODE, RED_CARD, YELLOW_CARD)
values ('ST001', 'M1001',  'MT001', 'SC0001', 1, 2)
into STATISTIC_MATCHS (STATISTIC_ID, MATCHS_MATCH_ID, PLAYERS_MANAGEMENT_ID, STATISTIC_CODE, RED_CARD, YELLOW_CARD)
values ('ST001', 'M1002',  'MT002', 'SC0002', 0, 2)
select * from dual

insert all 
into STATISTIC_MATCHS (STATISTIC_ID, MATCHS_MATCH_ID, PLAYERS_MANAGEMENT_ID, STATISTIC_CODE, RED_CARD, YELLOW_CARD)
values ('ST002', 'M1003',  'MT003', 'SC0003', 1, 2)
into STATISTIC_MATCHS (STATISTIC_ID, MATCHS_MATCH_ID, PLAYERS_MANAGEMENT_ID, STATISTIC_CODE, RED_CARD, YELLOW_CARD)
values ('ST002', 'M1004',  'MT004', 'SC0004', 0, 2)
select * from dual


select * from STATISTIC_MATCHS


========================================

STANDINGS

CREATE TABLE standings (
    standing_id      VARCHAR2(10)primary key,
    matches_played   INTEGER NOT NULL,
    win              INTEGER NOT NULL,
    drawn            INTEGER NOT NULL,
    lose             INTEGER NOT NULL,
    goals_for        INTEGER NOT NULL,
    goals_againts    INTEGER NOT NULL,
    goal_difference  INTEGER NOT NULL,
    points           INTEGER NOT NULL,
    matchs_match_id  VARCHAR2(10) NOT NULL,
    team_id          NUMBER(2), 
constraint stand_team_id_fk foreign key (team_id) references teams (team_id)
);

insert into standings  (standing_id, matches_played, win, drawn, lose, goals_for, goals_againts, goal_difference, points, matchs_match_id, team_id)
values ('ST001', 1, 1, 0, 0, 2, 0, 1, 3, 'M1001', 1)

insert into standings  (standing_id, matches_played, win, drawn, lose, goals_for, goals_againts, goal_difference, points, matchs_match_id, team_id)
values ('ST001', 1, 0, 0, 1, 1, 2, 1, 0, 'M1001', 2)

select * from standings

=====================================================

TTESTING

SELECT match_id, score, win, drawn, lose, goals_for, goals_againts, points, team_name
from matchs natural join standings natural join teams
where match_id = 'M1001'
order by match_id
             
select management_id, player_id, player_name, coach_id, coach_name 
from players natural join coaches
order by management_id

select status, match_name
from matchs
where status in ('Selesai', 'Belum Bertanding') 

select status, match_name
from matchs
where status in ('')
================================

CREATE INDEX teams_name_idx
ON teams(team_id, team_name, province);

SELECT DISTINCT ic.index_name, ic.column_name,
ic.column_position, id.uniqueness
FROM user_indexes id, user_ind_columns ic
WHERE id.table_name = ic.table_name
AND ic.table_name = 'TEAMS';

=====================================

CREATE VIEW view_players
AS SELECT player_id, player_name
FROM players 
WHERE player_id IN  ('P100', 'P200');


SELECT * FROM view_players

======================

CREATE SYNONYM wasit For referees

select * from wasit

=================

# settings = { language: "EN", APEX: true }

